//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2SERVER
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClimbersMountains
    {
        public int Id { get; set; }
        public Nullable<int> Climber_Id { get; set; }
        public Nullable<int> Mountain_Id { get; set; }
    
        public virtual Climbers Climbers { get; set; }
        public virtual Mountains Mountains { get; set; }
    }
}
