//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2SERVER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClimbersClubEntities : DbContext
    {
        public ClimbersClubEntities()
            : base("name=ClimbersClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Climbers> Climbers { get; set; }
        public virtual DbSet<ClimbersMountains> ClimbersMountains { get; set; }
        public virtual DbSet<Mountains> Mountains { get; set; }
    }
}
